import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Header from "./components/hearder-footer/Header";
import Footer from "./components/hearder-footer/Footer";
import { AuthProvider } from "./context/authContext";
import { ProductProvider } from "./context/productContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Shopi Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ProductProvider>
            <Header />
            {children}
            <Footer />
            <Toaster />
          </ProductProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
